.install-dependencies:
  before_script:
    - mkdir -p /usr/share/man/man1
    - apt update
    - apt install -y git wget libzip-dev sqlite3 libsqlite3-dev
    - docker-php-ext-install zip
    - docker-php-ext-install pdo pdo_sqlite
    - pecl install pcov
    - docker-php-ext-enable pcov
    - php --version
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
    - php composer.phar install

phpstan:
  extends:
    - .install-dependencies
  image: quay.imanuel.dev/dockerhub/library---php:8.1-cli
  stage: test
  services:
    - docker:dind
  script:
    - ./vendor/bin/phpstan --no-progress analyze ./src ./tests

phpunit:
  extends:
    - .install-dependencies
  image: quay.imanuel.dev/dockerhub/library---php:8.1-cli
  stage: test
  script:
    - ./vendor/bin/phpunit --log-junit report.xml --configuration ./phpunit.xml
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit:
        - report.xml