phpstan:
  image: harbor.ulbricht.casa/jinya/jinya-cms-php-base-test-image:latest
  stage: test
  script:
    - composer install
    - ./vendor/bin/phpstan --no-progress analyze ./src ./tests

phpunit:
  image: harbor.ulbricht.casa/jinya/jinya-cms-php-base-test-image:latest
  stage: test
  script:
    - composer install
    - install-php-extensions pdo pdo_sqlite pcov
    - ./vendor/bin/phpunit --log-junit report.xml --configuration ./phpunit.xml --coverage-text --coverage-cobertura=build/coverage.cobertura.xml
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit:
        - report.xml
      coverage_report:
        coverage_format: cobertura
        path: build/coverage.cobertura.xml

pages:
  stage: deploy
  image: harbor.ulbricht.casa/proxy/library/ruby:latest
  variables:
    JEKYLL_ENV: production
    LC_ALL: C.UTF-8
  before_script:
    - gem install bundler jekyll
    - bundle update rb-inotify
    - bundle install
  script:
    - bundle exec jekyll build -d public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH