# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: PDOx
description: PDOx, a small struct wrapper based on PDO
email: developers@jinya.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pdox.jinya.dev/" # the base hostname & protocol for your site, e.g. http://example.com

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

logo: assets/favicon.svg

remote_theme: BDHU/minimalist

favicon: true

sidebar:
  - name: PDOx Composer Package
    link: https://packagist.org/packages/jinya/pdox
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/Jinya-CMS/pdox/
  - name: GitLab
    icon: <i class="fa-brands fa-gitlab"></i>
    link: https://gitlab.imanuel.dev/jinya-cms/pdox/

exclude:
  - src
  - tests
  - vendor
  - composer.json
  - composer.lock
  - .gitlab-ci.yml
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - phpstan.neon
  - phpunit.xml