FROM quay.imanuel.dev/dockerhub/library---php:8.1-cli

RUN apt-get update
RUN apt-get install sqlite3 libsqlite3-dev
RUN docker-php-ext-install pdo pdo_sqlite
RUN pecl install pcov
RUN docker-php-ext-enable pcov